### ISSUE TITLE
Invalid int: "[]" when using setProgress

### ISSUE THREAD

**Issue by sam2x** [pwlin/cordova-plugin-pdialog#11]
Hey got the following stacktrace :

```
06-20 04:08:03.853 3900-3900/com.xxx.xxx E/AndroidRuntime: FATAL EXCEPTION: main
     Process: com.xxx.xxx, PID: 3900
     java.lang.NumberFormatException: Invalid int: "[]"
         at java.lang.Integer.invalidInt(Integer.java:138)
         at java.lang.Integer.parse(Integer.java:410)
         at java.lang.Integer.parseInt(Integer.java:367)
         at java.lang.Integer.parseInt(Integer.java:334)
         at io.github.pwlin.cordova.plugins.pdialog.PDialog$3.run(PDialog.java:192)
         at android.os.Handler.handleCallback(Handler.java:739)
         at android.os.Handler.dispatchMessage(Handler.java:95)
         at android.os.Looper.loop(Looper.java:148)
         at android.app.ActivityThread.main(ActivityThread.java:7331)
         at java.lang.reflect.Method.invoke(Native Method)
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

The error is suggesting that i passed an array, but I just used setProgress in a loop function with an integer parameter. Anyone experienced this ? 

     cordova.plugin.pDialog.setProgress(parseInt(100/(total/current)));

_Total_ and _current_ are positive integers (i care about zero division, so it's not that...).

The responsible source code seems good to me : 

	private void setProgress(final String rawArgs) {
		Runnable runnable = new Runnable() {
			@Override
			public void run() {
				int value = Integer.parseInt(rawArgs);
				PDialog.pDialogObj.setProgress(value);
			};
		};
		this.cordova.getActivity().runOnUiThread(runnable);
	}

Env: 

    Cordova 6.5.0
    Cordova android platform : 6.1.2
    Cordova-plugin-pdialog 2.0.1 "pDialog"

**Comment by sam2x** [comment]
Adding some debug to the code, i think i spotted the bug which deal about async operation. The API call to setprogress is called "too fast" in my loop, so a race condition seems to occurs, and it transforms the integer value to array. We need some callback/promise to be sure that the current setProgress has been correctly performed.

**Comment by sam2x** [comment]
I confirm the above theory. Using $interval circumvent this problem ;)
